<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Rules.fs" />
    <Compile Include="SimpleRules.fs" />
    <Compile Include="Game.fs" />
  </ItemGroup>

</Project>
